name: Scurlogue Champ
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39209325332194567
title: In Memory Of a Magnificent Canine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#232323'
    - '#7c7c7c'
    - '#9b9b9b'
    - '#cecece'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
