name: Scurlogue Champ
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76747
title: Scurlogue Champ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffecb1'
    - '#442f00'
    - '#000000'
    - '#8e6a2c'
    - '#bb9c63'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
