name: Scurlogue Champ
favicon: null
layout_spectrum: 0.49065
typography_spectrum: 0.76747
title: Scurlogue Champ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#32312f'
    - '#7d7e79'
    - '#aba49e'
    - '#fbf2ed'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
