name: Scurlogue Champ
favicon: null
layout_spectrum: 0.41100436937995255
typography_spectrum: 0.39209325332194567
title: In Memory Of a Magnificent Canine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
